.PHONY: clean All

All:
	@echo "----------Building project:[ SerialPortControl - Debug ]----------"
	@$(MAKE) -f  "SerialPortControl.mk"
clean:
	@echo "----------Cleaning project:[ SerialPortControl - Debug ]----------"
	@$(MAKE) -f  "SerialPortControl.mk" clean
